<a href="https://colab.research.google.com/github/johnny540/data_science540/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import numpy 
import numpy as np

In [2]:
# create a vector as a row in numy
vector_row = np.array([10,20,30,40,50])
print("Single row")
print(vector_row)

Single row
[10 20 30 40 50]


In [4]:
# create a single column in numpy
vector_column = np.array([[10],[20],[30],[40],[50]])
print("single column")
print(vector_column)

single column
[[10]
 [20]
 [30]
 [40]
 [50]]


In [6]:
#multi dimentional array
arr = np.array([[10,20],[30,40]])
print(arr)

[[10 20]
 [30 40]]


In [8]:
#selecting elements from vector or matrix
vector = np.array([10,20,30,40,50])
print(vector[0])
print(vector[1])
print(vector[2])

10
20
30


In [10]:
# select all elements of vector
vector = np.array([10,20,30,40,50])
print(vector[:])

[10 20 30 40 50]


In [20]:
# select elements by slicing
vector = np.array([10,20,30,40,50])
print(vector[:3])
print(vector[1:4])
print(vector[-1])
print(vector[-3])
print(vector[-2:])

[10 20 30]
[20 30 40]
50
30
[40 50]


In [22]:
# create two dimensional array which is called a matrix
matrix = np.array([[1,2],[1,2],[1,2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]
